export const RACE_DATA = {
  g1: [
    { name: "フェブラリーS", distance: 1600, track: "dirt", week: 7 },
    { name: "高松宮記念", distance: 1200, track: "turf", week: 13 },
    { name: "大阪杯", distance: 2000, track: "turf", week: 14 },
    { name: "桜花賞", distance: 1600, track: "turf", week: 15 },
    { name: "皐月賞", distance: 2000, track: "turf", week: 16 },
    { name: "天皇賞（春）", distance: 3200, track: "turf", week: 18 },
    { name: "NHKマイルC", distance: 1600, track: "turf", week: 19 },
    { name: "ヴィクトリアマイル", distance: 1600, track: "turf", week: 20 },
    { name: "オークス", distance: 2400, track: "turf", week: 21 },
    { name: "日本ダービー", distance: 2400, track: "turf", week: 22 },
    { name: "安田記念", distance: 1600, track: "turf", week: 23 },
    { name: "宝塚記念", distance: 2200, track: "turf", week: 26 },
    { name: "スプリンターズS", distance: 1200, track: "turf", week: 40 },
    { name: "秋華賞", distance: 2000, track: "turf", week: 42 },
    { name: "菊花賞", distance: 3000, track: "turf", week: 43 },
    { name: "天皇賞（秋）", distance: 2000, track: "turf", week: 44 },
    { name: "エリザベス女王杯", distance: 2200, track: "turf", week: 46 },
    { name: "マイルCS", distance: 1600, track: "turf", week: 47 },
    { name: "ジャパンC", distance: 2400, track: "turf", week: 48 },
    { name: "チャンピオンズC", distance: 1800, track: "dirt", week: 49 },
    { name: "阪神JF", distance: 1600, track: "turf", week: 50 },
    { name: "朝日杯FS", distance: 1600, track: "turf", week: 51 },
    { name: "有馬記念", distance: 2500, track: "turf", week: 52 },
    { name: "ホープフルS", distance: 2000, track: "turf", week: 52 },
  ],
  g2: [
    { name: "AJCC", distance: 2200, track: "turf", week: 4 },
    { name: "東海S", distance: 1800, track: "dirt", week: 4 },
    { name: "京都記念", distance: 2200, track: "turf", week: 6 },
    { name: "弥生賞", distance: 2000, track: "turf", week: 10 },
    { name: "フィリーズレビュー", distance: 1400, track: "turf", week: 11 },
    { name: "スプリングS", distance: 1800, track: "turf", week: 12 },
    { name: "阪神大賞典", distance: 3000, track: "turf", week: 12 },
    { name: "チューリップ賞", distance: 1600, track: "turf", week: 10 },
    { name: "マイラーズC", distance: 1600, track: "turf", week: 17 },
    { name: "青葉賞", distance: 2400, track: "turf", week: 18 },
    { name: "目黒記念", distance: 2500, track: "turf", week: 22 },
    { name: "鳴尾記念", distance: 2000, track: "turf", week: 23 },
    { name: "札幌記念", distance: 2000, track: "turf", week: 34 },
    { name: "セントウルS", distance: 1200, track: "turf", week: 37 },
    { name: "オールカマー", distance: 2200, track: "turf", week: 39 },
    { name: "神戸新聞杯", distance: 2400, track: "turf", week: 39 },
    { name: "毎日王冠", distance: 1800, track: "turf", week: 41 },
    { name: "府中牝馬S", distance: 1800, track: "turf", week: 42 },
    { name: "アルゼンチン共和国杯", distance: 2500, track: "turf", week: 45 },
    { name: "京都2歳S", distance: 2000, track: "turf", week: 48 },
    { name: "チャレンジC", distance: 2000, track: "turf", week: 49 },
  ],
  g3: [
    { name: "中山金杯", distance: 2000, track: "turf", week: 1 },
    { name: "京都金杯", distance: 1600, track: "turf", week: 1 },
    { name: "フェアリーS", distance: 1600, track: "turf", week: 2 },
    { name: "シンザン記念", distance: 1600, track: "turf", week: 2 },
    { name: "京成杯", distance: 2000, track: "turf", week: 3 },
    { name: "日経新春杯", distance: 2400, track: "turf", week: 3 },
    { name: "根岸S", distance: 1400, track: "dirt", week: 5 },
    { name: "きさらぎ賞", distance: 1800, track: "turf", week: 6 },
    { name: "東京新聞杯", distance: 1600, track: "turf", week: 6 },
    { name: "共同通信杯", distance: 1800, track: "turf", week: 7 },
    { name: "クイーンC", distance: 1600, track: "turf", week: 7 },
    { name: "ダイヤモンドS", distance: 3400, track: "turf", week: 7 },
    { name: "小倉大賞典", distance: 1800, track: "turf", week: 8 },
    { name: "中山牝馬S", distance: 1800, track: "turf", week: 11 },
    { name: "毎日杯", distance: 1800, track: "turf", week: 13 },
    { name: "アーリントンC", distance: 1600, track: "turf", week: 15 },
    { name: "マーガレットS", distance: 1400, track: "dirt", week: 15 },
    { name: "ニュージーランドT", distance: 1600, track: "turf", week: 15 },
    { name: "アンタレスS", distance: 1800, track: "dirt", week: 17 },
    { name: "福島牝馬S", distance: 1800, track: "turf", week: 19 },
    { name: "新潟大賞典", distance: 2000, track: "turf", week: 19 },
    { name: "葵S", distance: 1200, track: "turf", week: 22 },
    { name: "エプソムC", distance: 1800, track: "turf", week: 24 },
    { name: "ラジオNIKKEI賞", distance: 1800, track: "turf", week: 27 },
    { name: "函館2歳S", distance: 1200, track: "turf", week: 29 },
    { name: "函館記念", distance: 2000, track: "turf", week: 29 },
    { name: "クイーンS", distance: 1800, track: "turf", week: 31 },
    { name: "小倉記念", distance: 2000, track: "turf", week: 32 },
    { name: "北九州記念", distance: 1200, track: "turf", week: 35 },
    { name: "キーンランドC", distance: 1200, track: "turf", week: 35 },
    { name: "新潟2歳S", distance: 1600, track: "turf", week: 36 },
    { name: "京成杯AH", distance: 1600, track: "turf", week: 38 },
    { name: "シリウスS", distance: 2000, track: "dirt", week: 40 },
    { name: "福島記念", distance: 2000, track: "turf", week: 46 },
    { name: "愛知杯", distance: 2000, track: "turf", week: 50 },
    { name: "ターコイズS", distance: 1600, track: "turf", week: 51 },
    { name: "カペラS", distance: 1200, track: "dirt", week: 50 },
  ],
  listed: [
    { name: "ニューイヤーS", distance: 1600, track: "turf", week: 1 },
    { name: "初富士S", distance: 2000, track: "turf", week: 2 },
    { name: "洛陽S", distance: 1600, track: "turf", week: 6 },
    { name: "バレンタインS", distance: 1600, track: "dirt", week: 7 },
    { name: "白富士S", distance: 2000, track: "turf", week: 8 },
    { name: "コーラルS", distance: 1400, track: "dirt", week: 27 },
    { name: "レパードS", distance: 1900, track: "dirt", week: 31 },
    { name: "エニフS", distance: 1400, track: "dirt", week: 38 },
    { name: "グリーンチャンネルC", distance: 1400, track: "dirt", week: 16 },
    { name: "春雷S", distance: 1200, track: "turf", week: 21 },
    { name: "鞍馬S", distance: 1200, track: "turf", week: 19 },
    { name: "御堂筋S", distance: 1800, track: "dirt", week: 45 },
    { name: "ノベンバーS", distance: 1800, track: "turf", week: 45 },
    { name: "奥多摩S", distance: 1600, track: "dirt", week: 24 },
    { name: "サウジアラビアRC", distance: 1600, track: "turf", week: 41 },
    { name: "アルテミスS", distance: 1600, track: "turf", week: 43 },
  ],
  open: [
    { name: "松籟S", distance: 3000, track: "turf", week: 3 },
    { name: "エルムS", distance: 1700, track: "dirt", week: 33 },
    { name: "丹頂S", distance: 2000, track: "turf", week: 38 },
    { name: "スレイプニルS", distance: 2000, track: "dirt", week: 21 },
    { name: "オパールS", distance: 1200, track: "turf", week: 38 },
    { name: "ポートアイランドS", distance: 1600, track: "turf", week: 12 },
    { name: "谷川岳S", distance: 1600, track: "turf", week: 20 },
    { name: "都大路S", distance: 1800, track: "turf", week: 20 },
    { name: "米子S", distance: 1600, track: "turf", week: 29 },
    { name: "BSN賞", distance: 2000, track: "turf", week: 30 },
    { name: "プリンシパルS", distance: 2000, track: "turf", week: 20 },
  ],
};

export const GRADE_LABELS = {
  shinjuba: '新馬戦',
  mishousen: '未勝利戦',
  '1sho': '1勝クラス',
  '2sho': '2勝クラス',
  '3sho': '3勝クラス',
  listed: 'L',
  open: 'OP',
  g3: 'G3',
  g2: 'G2',
  g1: 'G1',
};

export const GRADE_PRIZES = {
  shinjuba: 200000,
  mishousen: 100000,
  '1sho': 200000,
  '2sho': 350000,
  '3sho': 500000,
  listed: 300000,
  open: 600000,
  g3: 1500000,
  g2: 3000000,
  g1: 10000000,
};

export function getRacesForWeek(currentWeek, availableGrades) {
  const races = [];
  const fixedGrades = ['shinjuba','mishousen','1sho','2sho','3sho'];
  const fixedDistances = [
    { distance: 1600, track: 'turf' },
    { distance: 1600, track: 'dirt' },
    { distance: 2000, track: 'turf' },
    { distance: 2000, track: 'dirt' },
    { distance: 2400, track: 'turf' },
    { distance: 2400, track: 'dirt' },
  ];

  for (const grade of availableGrades) {
    if (fixedGrades.includes(grade)) {
      fixedDistances.forEach(r => races.push({ ...r, name: 'フィクションレース', grade }));
    } else {
      const gradeRaces = RACE_DATA[grade] ?? [];
      const weekRaces = gradeRaces.filter(r => r.week === currentWeek);
      weekRaces.forEach(r => races.push({ ...r, grade }));
    }
  }

  return races;
}
